### ISSUE TITLE
OpenCore 0.7

### ISSUE THREAD

**Issue by amirmeimari** [cstefann/Lenovo-530s-15IKB-hackintosh#1]
Can you update this repo to use the latest OpenCore (0.7 at the moment) and the latest drivers and kext for BugSur? Thanks.

**Comment by cstefann** [comment]
Hello @amirmeimari !
I just updated the OC bootloader and the kexts.
As I just wrote on the README section, the development on this repo will be halted because I don't own this device anymore.
Thank you for your interest! Best regards!
